### ISSUE TITLE
Doesn't build with nettle 3.5.1

### ISSUE THREAD

**Issue by jonringer** [arpa2/gnutls-kdh#2]
Trying to build the package with nettle 3.5.1 but get the following build error:

```
aes-padlock.c:96:29: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                             ^~~~
                             key_size
aes-padlock.c:96:45: error: 'struct aes_ctx' has no member named 'keys'; did you mean 'key_size'?
   memcpy(pce->ks.rd_key, nc.keys, sizeof(nc.keys));
                                             ^~~~
                                             key_size
aes-padlock.c:97:22: error: 'struct aes_ctx' has no member named 'rounds'
   pce->ks.rounds = nc.rounds;
                      ^
make[5]: *** [Makefile:1587: aes-padlock.lo] Error 1
make[5]: Leaving directory '/build/source/lib/accelerated/x86'
make[4]: *** [Makefile:1423: all-recursive] Error 1
make[4]: Leaving directory '/build/source/lib/accelerated'
make[3]: *** [Makefile:1849: all-recursive] Error 1
make[3]: Leaving directory '/build/source/lib'
make[2]: *** [Makefile:1578: all] Error 2
make[2]: Leaving directory '/build/source/lib'
make[1]: *** [Makefile:1400: all-recursive] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:1328: all] Error 2
```

**Comment by jonringer** [comment]
closing due to inactivity

**Comment by vanrein** [comment]
Jon,

Sorry about having put this on hold.  We are mostly involved with the spec at the moment, trying to get it into an RFC.  The code is guided by that process.  You're a bit early to adopt I fear, this is for now work for an Internet Draft.

-Rick

**Comment by jonringer** [comment]
just doing some personal PR/issue upkeep noticed this was stale for 5+ months.
